application:
  mode: debug #gin的启动模式， debug or release or test
  server:
    port: 8888
    name: skdp-admin-service
  #数据库连接
  db:
    ConnectionString: root:root@tcp(127.0.0.1:3307)/skdp?parseTime=true